### ISSUE TITLE
以pr为基础的协作方式

### ISSUE THREAD

**Issue by MC-XiaoHei** [mc-meme/mc-meme#17]
方案特点
- 通过pr来实现新图片的添加（只需要添加图片，故没有冲突风险）
- 通过actions，使用java等语言，二维装箱等算法自动生成大图
- 发布到仓库单独分支（可以上传gh pages）
- 统一使用png格式，处理方便且功能强大
- 对项目类型进行简单分类，例如加载器，插件端，混合端等

我个人不推荐把格式限制太死，字体的设计以及位置都可以是meme的点，如果仅仅是提交图片很多问题就简化了
各位有什么其他建议吗（
我会自行尝试实现此想法

**Comment by MC-XiaoHei** [comment]
排序算法目前已经很成熟了，可以直接用

**Comment by LIPiston** [comment]
这是好的，没去了解过二维装箱的算法。
到时候看看

**Comment by MC-XiaoHei** [comment]
> 这是好的，没去了解过二维装箱的算法。
> 到时候看看

那我就做了（
到时候看看发个pr，单独开个分支
感谢认可

**Comment by MC-XiaoHei** [comment]
还有个好处，png是无损压缩，不会导致糊，到时候输出可以一份png一份jpg

**Comment by SnowCutieOwO** [comment]
也可以试试 miroboard 那种在线编辑式的，我个人觉得挺好 有时候需要了还可以贴散装弔图上去（

**Comment by MC-XiaoHei** [comment]
> 也可以试试 miroboard 那种在线编辑式的，我个人觉得挺好 有时候需要了还可以贴散装弔图上去（

这种最关键问题是难以控制权限

**Comment by MC-XiaoHei** [comment]
草 你们做完了

**Comment by autumn-2-net** [comment]
说实话 你可以在现有的基础上改进下 毕竟目前的自动打包还是有点难绷（

**Comment by MC-XiaoHei** [comment]
> 说实话 你可以在现有的基础上改进下 毕竟目前的自动打包还是有点难绷（

我其实写完了（
看owner吧
目前已经能实现自动把每个文件夹的图片都合并，用的是天际线算法

**Comment by autumn-2-net** [comment]
不啊  你先展示下效果（

**Comment by autumn-2-net** [comment]
效果好可以直接换（

**Comment by MC-XiaoHei** [comment]
> 不啊 你先展示下效果（

我抽空弄一下吧。高三生 哎

**Comment by MC-XiaoHei** [comment]
> 说实话 你可以在现有的基础上改进下 毕竟目前的自动打包还是有点难绷（

你们现在的方案是有啥问题吗（

**Comment by autumn-2-net** [comment]
现在是根据图片大小来排序的（
有人觉得应该把相关图放一起（
反正最后出来图挺难崩的
最开始版本是按照文件名排序
然后经常会产生有超大量空白的图片

**Comment by MC-XiaoHei** [comment]
我的算法也是大概按照图片大小来排序（这个问题可以分不同的大图解决
但是好处是应该不会有很多空白（？
我试试

**Comment by MC-XiaoHei** [comment]
![test](https://github.com/user-attachments/assets/db5edcae-7f1f-4a95-a2eb-b604c55db39c)
感觉效果也不是很好 好像是因为有些图像的大小过大？我算法是没有自动缩放的，然后固定高度（之前想的是放网站上可以左右拖动

**Comment by MC-XiaoHei** [comment]
但是我个人感觉这个算法的体感空白更小
edit: 你们应该能看到这个图吧

**Comment by autumn-2-net** [comment]
所以你这是固定了图片的高度？ 
我实现的倒是长宽自适应
你这个图我感觉哪里怪怪的
好像这样排出来比主页上看起来更乱点[Screenshot_20241015_155613_com.github.android.jpg](https://github.com/user-attachments/assets/c54a4b9d-dc58-4c6b-84a1-18b6ad22b1d8)
   好像主页上的效果貌似好点
要不你改成自适应长宽试试？

**Comment by MC-XiaoHei** [comment]
> 所以你这是固定了图片的高度？ 
> 我实现的倒是长宽自适应
> 你这个图我感觉哪里怪怪的
> 好像这样排出来比主页上看起来更乱点[Screenshot_20241015_155613_com.github.android.jpg](https://github.com/user-attachments/assets/c54a4b9d-dc58-4c6b-84a1-18b6ad22b1d8)
>    好像主页上的效果貌似好点
> 要不你改成自适应长宽试试？
> 

自适应我没啥思路搞（
有个办法是多试几个直到利用率最高
我这个看起来乱可能是因为左半边利用率比较高（

**Comment by MC-XiaoHei** [comment]
反正我这个算法是很快的，处理一次不到一秒（具体没测
