### ISSUE TITLE
建议添加并标注三、四改版来源

### ISSUE THREAD

**Issue by ghost** [mc-meme/mc-meme#5]
首先感谢原作者的图，启发灵感（（（

其次就是，三改版（此图）

![新建项目 (6)](https://github.com/user-attachments/assets/7fa6768a-0f3f-4f5e-8896-9c8e0a886eb1)

及四改版（此图）

![绷](https://github.com/user-attachments/assets/6d797b71-9c95-42d7-ad23-5ff318e53525)

都是我拓展的（（

三改由我出鬼点子并拓展

四改的鬼点子来源于我、阳帆（ @WolfYangFan ）、还有OBA（OpenBMCLAPI）群友，并由我拓展

毕竟不是我自己的主意，所以建议标注下，并添加至仓库

**Comment by ghost** [comment]
正确的流程应该是这样：

原版：四宫格

二改（这个不知道是谁改的）：添加网易及datapack

三改：添加插件系端及部分混合端

四改（：添加跨服端、mcdr、部分启动器、多线程端，补全部分mod、混合端

**Comment by LIPiston** [comment]
已经添加，所以关闭此issue
