### ISSUE TITLE
Add a license & AUTHORS.md

### ISSUE THREAD

**Issue by chun-awa** [mc-meme/mc-meme#6]
考虑[CC BY](https://creativecommons.org/licenses/by/4.0/deed.en)，[CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/deed.en)之类的（？

**Comment by LIPiston** [comment]
加！

**Comment by chun-awa** [comment]
这玩意越早加越好，找到所有原作者看看同不同意使用同一个license，最后搞个`AUTHORS.md`列出所有作者并指出贡献的对应部分

**Comment by LIPiston** [comment]
打算用CC-BY-NC-SA 4.0

**Comment by LIPiston** [comment]
已经加了所以关了
